{% set name = "sqlalchemy-cockroachdb" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-cockroachdb-{{ version }}.tar.gz
  sha256: 119756eb905855d6a11345b99cfe853031a3fe598a9c4bf35a8ddac9f89fe8cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - psycopg2
    - sqlalchemy >=2.0.0

test:
  imports:
    - sqlalchemy_cockroachdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cockroachdb/sqlalchemy-cockroachdb
  summary: CockroachDB dialect for SQLAlchemy
  dev_url: https://github.com/cockroachdb/sqlalchemy-cockroachdb
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
