{% set name = "sqlalchemy-cockroachdb" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-cockroachdb-{{ version }}.tar.gz
  sha256: bc3def9ea61c55ff7579cd9f75918a108af66db65981fcc2e638b6866fdaf0a7
  patches:
    - 0001-Specify-UTF-8-Encoding-when-reading-files-during-set.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - psycopg2
    - sqlalchemy >=2.0.0

test:
  imports:
    - sqlalchemy_cockroachdb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cockroachdb/sqlalchemy-cockroachdb
  summary: CockroachDB dialect for SQLAlchemy
  dev_url: https://github.com/cockroachdb/sqlalchemy-cockroachdb
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
